version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    groups:
      pip-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/cli"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    groups:
      cli-npm-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/dashboard"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    groups:
      dashboard-npm-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    groups:
      docker-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      actions-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
