"""Add progress columns to scans table

Revision ID: 1b21aeb48f28
Revises: 2025_11_09_pa11y
Create Date: 2025-11-03 05:55:54.595270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1b21aeb48f28"
down_revision: Union[str, None] = "2025_11_09_pa11y"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_wcag_criterion", table_name="wcag_guidelines")
    op.drop_index("idx_wcag_level", table_name="wcag_guidelines")
    op.drop_index("idx_wcag_rule_id", table_name="wcag_guidelines")
    op.drop_table("wcag_guidelines")
    op.add_column("scans", sa.Column("progress", sa.Integer(), nullable=True))
    op.add_column("scans", sa.Column("progress_message", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scans", "progress_message")
    op.drop_column("scans", "progress")
    op.create_table(
        "wcag_guidelines",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "rule_id", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "wcag_criterion", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "wcag_level", sa.VARCHAR(length=5), autoincrement=False, nullable=False
        ),
        sa.Column(
            "wcag_version",
            sa.VARCHAR(length=10),
            server_default=sa.text("'2.2'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "principle", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "guideline", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "severity_criteria",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "business_impact_template", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column("technical_impact", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "fix_examples",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "best_practices",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.TEXT()),
            server_default=sa.text("'{}'::text[]"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "act_rule_ids",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "related_rules",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "embedding",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="wcag_guidelines_pkey"),
        sa.UniqueConstraint("rule_id", name="wcag_guidelines_rule_id_key"),
    )
    op.create_index("idx_wcag_rule_id", "wcag_guidelines", ["rule_id"], unique=False)
    op.create_index("idx_wcag_level", "wcag_guidelines", ["wcag_level"], unique=False)
    op.create_index(
        "idx_wcag_criterion", "wcag_guidelines", ["wcag_criterion"], unique=False
    )
    # ### end Alembic commands ###
