"""
Complete WCAG Knowledge Base Seed Data - All 127 axe-core Rules

This module contains ALL axe-core rules for comprehensive WCAG 2.2 coverage:
- 82 WCAG 2.0 Level A & AA rules
- 2 WCAG 2.1 Level A & AA rules
- 1 WCAG 2.2 Level A & AA rule
- 28 Best Practices rules
- 3 WCAG 2.x Level AAA rules
- 7 Experimental rules
- 4 Deprecated rules

Based on axe-core 4.10+ rule set.
For rule details, see: https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md
"""

# Import existing detailed rules
from .wcag_seed_data import WCAG_GUIDELINES as DETAILED_RULES
from .wcag_seed_data_extended import EXTENDED_WCAG_GUIDELINES, generic_severity_criteria
from .wcag_human_descriptions import get_human_description_pair


# Helper function to create rule entry
def create_rule(
    rule_id,
    wcag_criterion,
    wcag_level,
    title,
    description,
    principle,
    guideline,
    severity_type="general",
    tags=None,
    act_rule_ids=None,
    related_rules=None,
):
    """Helper to create rule entry with consistent structure"""
    # Get human-friendly descriptions from mapping
    human_desc = get_human_description_pair(
        wcag_criterion=wcag_criterion, rule_id=rule_id
    )

    return {
        "rule_id": rule_id,
        "wcag_criterion": wcag_criterion,
        "wcag_level": wcag_level,
        "title": title,
        "description": description,
        "principle": principle,
        "guideline": guideline,
        "severity_criteria": generic_severity_criteria(severity_type),
        "business_impact_template": f"Violates WCAG 2.2 Level {wcag_level} ({wcag_criterion}). {description}",
        "technical_impact": "Screen readers or assistive technology may not properly interpret this element. Automated testing flags as WCAG violation.",
        "fix_examples": [],
        "best_practices": [
            "Follow WCAG 2.2 guidelines",
            "Test with assistive technology",
            "Use automated testing tools",
        ],
        "tags": tags
        or [
            "wcag2" + wcag_level.lower(),
            f"wcag{wcag_criterion.replace('.', '')}",
            "axe-core",
        ],
        "human_issue": human_desc["issue"] if human_desc else None,
        "human_fixed": human_desc["fixed"] if human_desc else None,
        "act_rule_ids": act_rule_ids or [],
        "related_rules": related_rules or [],
    }


# Additional rules not covered in DETAILED_RULES or EXTENDED_WCAG_GUIDELINES
ADDITIONAL_WCAG_RULES = [
    # WCAG 2.0 Level A & AA Rules (continuing from existing)
    create_rule(
        "area-alt",
        "2.4.4",
        "A",
        "Active <area> elements must have alternate text",
        "Ensures <area> elements of image maps have alternate text. Image map areas must describe their purpose for screen reader users.",
        "Operable",
        "2.4 Navigable",
        "semantic",
        ["wcag2a", "wcag244", "wcag412", "section508", "axe-core"],
    ),
    create_rule(
        "aria-braille-equivalent",
        "1.1.1",
        "A",
        "aria-braillelabel and aria-brailleroledescription must have non-braille equivalent",
        "Ensures every aria-braillelabel has a non-empty aria-label, and every aria-brailleroledescription has a non-empty aria-roledescription. Braille-specific attributes need text equivalents.",
        "Perceivable",
        "1.1 Text Alternatives",
        "aria",
        ["wcag2a", "wcag111", "aria", "axe-core"],
    ),
    create_rule(
        "aria-command-name",
        "4.1.2",
        "A",
        "ARIA commands must have accessible names",
        "Ensures elements with role=button, role=link, or role=menuitem have accessible names. Interactive ARIA widgets need descriptive names.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["wcag2a", "wcag412", "aria", "axe-core"],
    ),
    create_rule(
        "aria-conditional-attr",
        "4.1.2",
        "A",
        "ARIA attributes must be used with appropriate roles",
        "Ensures ARIA attributes that are conditionally required are present when needed. Some ARIA attributes are only valid in specific contexts.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["wcag2a", "wcag412", "aria", "axe-core"],
    ),
    create_rule(
        "aria-deprecated-role",
        "4.1.2",
        "A",
        "Deprecated ARIA roles should not be used",
        "Ensures deprecated ARIA roles are not used. Deprecated roles may not be supported by assistive technologies.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["wcag2a", "wcag412", "aria", "axe-core"],
    ),
    create_rule(
        "aria-dialog-name",
        "4.1.2",
        "A",
        "ARIA dialog and alertdialog must have accessible names",
        "Ensures elements with role=dialog or role=alertdialog have accessible names. Dialogs need names to identify their purpose.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["wcag2a", "wcag412", "aria", "axe-core"],
    ),
    create_rule(
        "aria-hidden-body",
        "4.1.2",
        "A",
        "aria-hidden='true' must not be present on body",
        "Ensures aria-hidden='true' is not present on document body. Hiding the entire page from screen readers makes content inaccessible.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["wcag2a", "wcag412", "aria", "axe-core"],
    ),
    create_rule(
        "aria-hidden-focus",
        "4.1.2",
        "A",
        "Elements with aria-hidden='true' must not contain focusable elements",
        "Ensures aria-hidden elements do not contain focusable elements. Keyboard users can focus elements that screen readers cannot read.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["wcag2a", "wcag412", "aria", "axe-core"],
    ),
    create_rule(
        "aria-input-field-name",
        "4.1.2",
        "A",
        "ARIA input fields must have accessible names",
        "Ensures ARIA input fields have accessible names. Input fields need labels for screen reader users.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["wcag2a", "wcag412", "aria", "forms", "axe-core"],
    ),
    create_rule(
        "aria-meter-name",
        "1.1.1",
        "A",
        "ARIA meter elements must have accessible names",
        "Ensures <meter> or elements with role=meter have accessible names. Meters need names to describe what they measure.",
        "Perceivable",
        "1.1 Text Alternatives",
        "aria",
        ["wcag2a", "wcag111", "aria", "axe-core"],
    ),
    create_rule(
        "aria-progressbar-name",
        "1.1.1",
        "A",
        "ARIA progressbar elements must have accessible names",
        "Ensures <progressbar> or elements with role=progressbar have accessible names. Progress bars need names to describe their purpose.",
        "Perceivable",
        "1.1 Text Alternatives",
        "aria",
        ["wcag2a", "wcag111", "aria", "axe-core"],
    ),
    create_rule(
        "aria-prohibited-attr",
        "4.1.2",
        "A",
        "ARIA attributes must not be used where prohibited",
        "Ensures ARIA attributes are not used where they are prohibited. Some ARIA attributes conflict with native semantics.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["wcag2a", "wcag412", "aria", "axe-core"],
    ),
    create_rule(
        "aria-required-children",
        "1.3.1",
        "A",
        "ARIA roles requiring child roles must have them",
        "Ensures elements with ARIA roles that require child roles contain them. Role relationships must be properly structured.",
        "Perceivable",
        "1.3 Adaptable",
        "aria",
        ["wcag2a", "wcag131", "aria", "axe-core"],
    ),
    create_rule(
        "aria-required-parent",
        "1.3.1",
        "A",
        "ARIA roles requiring parent roles must be contained by them",
        "Ensures elements with ARIA roles that require parent roles are contained by them. Child roles must have appropriate parents.",
        "Perceivable",
        "1.3 Adaptable",
        "aria",
        ["wcag2a", "wcag131", "aria", "axe-core"],
    ),
    create_rule(
        "aria-roledescription",
        "4.1.2",
        "A",
        "aria-roledescription must be on elements with semantic roles",
        "Ensures aria-roledescription is only used on elements with implicit or explicit role values. Role descriptions need roles to describe.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["wcag2a", "wcag412", "aria", "axe-core"],
    ),
    create_rule(
        "aria-roles",
        "4.1.2",
        "A",
        "ARIA role must be valid",
        "Ensures all elements with role attribute use valid ARIA role value. Invalid roles are ignored by assistive technologies.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["wcag2a", "wcag412", "aria", "axe-core"],
    ),
    create_rule(
        "aria-text",
        "4.1.2",
        "A",
        "role='text' elements must not contain interactive content",
        "Ensures role='text' is not used on elements that should be interactive. Text role removes all semantic information.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["wcag2a", "wcag412", "aria", "axe-core"],
    ),
    create_rule(
        "aria-toggle-field-name",
        "4.1.2",
        "A",
        "ARIA toggle fields must have accessible names",
        "Ensures elements with role=checkbox, role=radio, or role=switch have accessible names. Toggle controls need labels.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["wcag2a", "wcag412", "aria", "forms", "axe-core"],
    ),
    create_rule(
        "aria-tooltip-name",
        "4.1.2",
        "A",
        "ARIA tooltip elements must have accessible names",
        "Ensures elements with role=tooltip have accessible names. Tooltips need names to convey their content.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["wcag2a", "wcag412", "aria", "axe-core"],
    ),
    create_rule(
        "aria-treeitem-name",
        "4.1.2",
        "A",
        "ARIA treeitem elements must have accessible names",
        "Ensures elements with role=treeitem have accessible names. Tree items need labels for screen reader users.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["wcag2a", "wcag412", "aria", "axe-core"],
    ),
    create_rule(
        "blink",
        "2.2.2",
        "A",
        "<blink> elements are deprecated and should not be used",
        "Ensures <blink> elements are not used. Blinking content is distracting and can cause seizures.",
        "Operable",
        "2.2 Enough Time",
        "semantic",
        ["wcag2a", "wcag222", "axe-core"],
    ),
    create_rule(
        "definition-list",
        "1.3.1",
        "A",
        "Definition lists must be correctly structured",
        "Ensures <dl> elements are structured correctly. Definition lists must contain only <dt> and <dd> elements.",
        "Perceivable",
        "1.3 Adaptable",
        "semantic",
        ["wcag2a", "wcag131", "axe-core"],
    ),
    create_rule(
        "dlitem",
        "1.3.1",
        "A",
        "Definition list items must be inside <dl> elements",
        "Ensures <dt> and <dd> elements are contained by <dl>. List items must be inside list containers.",
        "Perceivable",
        "1.3 Adaptable",
        "semantic",
        ["wcag2a", "wcag131", "axe-core"],
    ),
    create_rule(
        "duplicate-id-active",
        "4.1.1",
        "A",
        "IDs of active elements must be unique",
        "Ensures every id attribute value of active elements is unique. Duplicate IDs on interactive elements break assistive technology.",
        "Robust",
        "4.1 Compatible",
        "semantic",
        ["wcag2a", "wcag411", "axe-core"],
    ),
    create_rule(
        "duplicate-id-aria",
        "4.1.2",
        "A",
        "IDs used in ARIA must be unique",
        "Ensures every id attribute value used in ARIA and labels is unique. Duplicate IDs break ARIA relationships.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["wcag2a", "wcag412", "aria", "axe-core"],
    ),
    create_rule(
        "form-field-multiple-labels",
        "3.3.2",
        "A",
        "Form fields should not have multiple label elements",
        "Ensures form field does not have multiple label elements. Multiple labels confuse assistive technology.",
        "Understandable",
        "3.3 Input Assistance",
        "form",
        ["wcag2a", "wcag332", "forms", "axe-core"],
    ),
    create_rule(
        "frame-title",
        "4.1.2",
        "A",
        "Frames must have title attributes",
        "Ensures <iframe> and <frame> elements have unique titles. Frame titles help users understand frame content.",
        "Robust",
        "4.1 Compatible",
        "semantic",
        ["wcag2a", "wcag412", "section508", "axe-core"],
    ),
    create_rule(
        "html-xml-lang-mismatch",
        "3.1.1",
        "A",
        "HTML and XML lang attributes must match",
        "Ensures HTML and XML lang attributes have the same value. Mismatched language codes confuse assistive technology.",
        "Understandable",
        "3.1 Readable",
        "semantic",
        ["wcag2a", "wcag311", "axe-core"],
    ),
    create_rule(
        "image-redundant-alt",
        "1.1.1",
        "A",
        "Image alt text should not be redundant",
        "Ensures image alt text does not repeat as text. Redundant alt text creates poor experience for screen reader users.",
        "Perceivable",
        "1.1 Text Alternatives",
        "semantic",
        ["wcag2a", "wcag111", "axe-core"],
    ),
    create_rule(
        "input-image-alt",
        "1.1.1",
        "A",
        "Image buttons must have alt text",
        "Ensures <input type='image'> elements have alt text. Image buttons need text alternatives.",
        "Perceivable",
        "1.1 Text Alternatives",
        "form",
        ["wcag2a", "wcag111", "section508", "forms", "axe-core"],
    ),
    create_rule(
        "label-content-name-mismatch",
        "2.5.3",
        "A",
        "Label text must match accessible name",
        "Ensures visible label text is part of accessible name. Mismatched labels confuse voice control users.",
        "Operable",
        "2.5 Input Modalities",
        "form",
        ["wcag21a", "wcag253", "forms", "axe-core"],
    ),
    create_rule(
        "link-in-text-block",
        "1.4.1",
        "A",
        "Links must be distinguishable without relying on color",
        "Ensures links in text blocks are distinguished visually. Links must be identifiable by more than just color.",
        "Perceivable",
        "1.4 Distinguishable",
        "general",
        ["wcag2a", "wcag141", "axe-core"],
    ),
    create_rule(
        "marquee",
        "2.2.2",
        "A",
        "<marquee> elements are deprecated and should not be used",
        "Ensures <marquee> elements are not used. Marquee creates moving content that can be distracting or cause seizures.",
        "Operable",
        "2.2 Enough Time",
        "semantic",
        ["wcag2a", "wcag222", "axe-core"],
    ),
    create_rule(
        "meta-refresh",
        "2.2.1",
        "A",
        "Timed meta refresh must not exist",
        "Ensures <meta http-equiv='refresh'> is not used for timed refresh. Auto-refresh removes user control.",
        "Operable",
        "2.2 Enough Time",
        "semantic",
        ["wcag2a", "wcag221", "axe-core"],
    ),
    create_rule(
        "meta-refresh-no-exceptions",
        "2.2.4",
        "AAA",
        "Meta refresh should not be used",
        "Ensures <meta http-equiv='refresh'> is not used at all (AAA). Meta refresh removes user control over navigation.",
        "Operable",
        "2.2 Enough Time",
        "semantic",
        ["wcag2aaa", "wcag224", "axe-core"],
    ),
    create_rule(
        "meta-viewport",
        "1.4.4",
        "AA",
        "Zooming and scaling must not be disabled",
        "Ensures <meta name='viewport'> does not disable zooming. Users with low vision need zoom functionality.",
        "Perceivable",
        "1.4 Distinguishable",
        "semantic",
        ["wcag2aa", "wcag144", "axe-core"],
    ),
    create_rule(
        "meta-viewport-large",
        "1.4.4",
        "AA",
        "Zoom must allow at least 200% scaling",
        "Ensures <meta name='viewport'> allows 200%+ zoom. Users with low vision need 2x magnification minimum.",
        "Perceivable",
        "1.4 Distinguishable",
        "semantic",
        ["wcag2aa", "wcag144", "axe-core"],
    ),
    create_rule(
        "nested-interactive",
        "4.1.2",
        "A",
        "Interactive elements must not contain other interactive elements",
        "Ensures interactive controls are not nested. Nested interactive elements confuse assistive technology.",
        "Robust",
        "4.1 Compatible",
        "semantic",
        ["wcag2a", "wcag412", "axe-core"],
    ),
    create_rule(
        "no-autoplay-audio",
        "1.4.2",
        "A",
        "Audio must not play automatically",
        "Ensures <video> or <audio> elements do not autoplay for >3 seconds. Auto-playing audio interferes with screen readers.",
        "Perceivable",
        "1.4 Distinguishable",
        "media",
        ["wcag2a", "wcag142", "axe-core"],
    ),
    create_rule(
        "object-alt",
        "1.1.1",
        "A",
        "<object> elements must have text alternatives",
        "Ensures <object> elements have alt text. Objects need text alternatives for screen reader users.",
        "Perceivable",
        "1.1 Text Alternatives",
        "semantic",
        ["wcag2a", "wcag111", "section508", "axe-core"],
    ),
    create_rule(
        "role-img-alt",
        "1.1.1",
        "A",
        "Elements with role='img' must have alt text",
        "Ensures [role='img'] elements have alt text via aria-label or aria-labelledby. Images need text alternatives.",
        "Perceivable",
        "1.1 Text Alternatives",
        "aria",
        ["wcag2a", "wcag111", "aria", "axe-core"],
    ),
    create_rule(
        "scope-attr-valid",
        "1.3.1",
        "A",
        "scope attribute must be used correctly on tables",
        "Ensures scope attribute is only used on table header elements. Scope defines header/data cell relationships.",
        "Perceivable",
        "1.3 Adaptable",
        "semantic",
        ["wcag2a", "wcag131", "tables", "axe-core"],
    ),
    create_rule(
        "scrollable-region-focusable",
        "2.1.1",
        "A",
        "Scrollable regions must be keyboard accessible",
        "Ensures scrollable regions can be accessed by keyboard. Scrollable areas need to be focusable.",
        "Operable",
        "2.1 Keyboard Accessible",
        "general",
        ["wcag2a", "wcag211", "keyboard", "axe-core"],
    ),
    create_rule(
        "server-side-image-map",
        "2.1.1",
        "A",
        "Server-side image maps should not be used",
        "Ensures server-side image maps are not used. Server-side maps are not keyboard accessible.",
        "Operable",
        "2.1 Keyboard Accessible",
        "semantic",
        ["wcag2a", "wcag211", "axe-core"],
    ),
    create_rule(
        "svg-img-alt",
        "1.1.1",
        "A",
        "SVG images must have text alternatives",
        "Ensures <svg> elements with role='img' have accessible names. SVG images need text alternatives.",
        "Perceivable",
        "1.1 Text Alternatives",
        "semantic",
        ["wcag2a", "wcag111", "axe-core"],
    ),
    create_rule(
        "td-has-header",
        "1.3.1",
        "A",
        "Table data cells should have headers",
        "Ensures all non-empty data cells have table headers. Data cells need headers for context.",
        "Perceivable",
        "1.3 Adaptable",
        "semantic",
        ["wcag2a", "wcag131", "tables", "axe-core"],
    ),
    create_rule(
        "td-headers-attr",
        "1.3.1",
        "A",
        "headers attribute must reference table cells",
        "Ensures headers attribute on data cells references table header cells. Headers attribute creates cell relationships.",
        "Perceivable",
        "1.3 Adaptable",
        "semantic",
        ["wcag2a", "wcag131", "tables", "axe-core"],
    ),
    create_rule(
        "valid-lang",
        "3.1.2",
        "AA",
        "lang attributes must have valid values",
        "Ensures lang attributes have valid language codes. Invalid language codes break screen reader pronunciation.",
        "Understandable",
        "3.1 Readable",
        "semantic",
        ["wcag2aa", "wcag312", "axe-core"],
    ),
    # Best Practice Rules (not required for WCAG compliance but recommended)
    create_rule(
        "accesskeys",
        "2.4.1",
        "A",
        "accesskey values should be unique",
        "Ensures accesskey attribute values are unique. Duplicate access keys create conflicts.",
        "Operable",
        "2.4 Navigable",
        "general",
        ["best-practice", "keyboard", "axe-core"],
    ),
    create_rule(
        "aria-allowed-role",
        "4.1.2",
        "A",
        "ARIA role should be appropriate for element",
        "Ensures role attribute is appropriate for element. Some roles override native semantics.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["best-practice", "aria", "axe-core"],
    ),
    create_rule(
        "duplicate-id",
        "4.1.1",
        "A",
        "IDs should be unique",
        "Ensures every id attribute value is unique. Duplicate IDs can cause issues with CSS and JavaScript.",
        "Robust",
        "4.1 Compatible",
        "semantic",
        ["best-practice", "axe-core"],
    ),
    create_rule(
        "frame-focusable-content",
        "2.1.1",
        "A",
        "Frames with focusable content must not have tabindex=-1",
        "Ensures frames with focusable content can receive keyboard focus. Hidden frames block keyboard navigation.",
        "Operable",
        "2.1 Keyboard Accessible",
        "semantic",
        ["best-practice", "keyboard", "axe-core"],
    ),
    create_rule(
        "frame-title-unique",
        "4.1.2",
        "A",
        "Frame titles should be unique",
        "Ensures frame titles are unique. Duplicate frame titles confuse screen reader users.",
        "Robust",
        "4.1 Compatible",
        "semantic",
        ["best-practice", "axe-core"],
    ),
    create_rule(
        "hidden-content",
        "4.1.2",
        "A",
        "Hidden content should not be focusable",
        "Ensures hidden content (display:none, visibility:hidden) is not focusable. Invisible content shouldn't receive focus.",
        "Robust",
        "4.1 Compatible",
        "general",
        ["best-practice", "keyboard", "axe-core"],
    ),
    create_rule(
        "image-alt-length",
        "1.1.1",
        "A",
        "Image alt text should be concise",
        "Ensures image alt text is concise (under 150 characters). Long alt text creates poor screen reader experience.",
        "Perceivable",
        "1.1 Text Alternatives",
        "semantic",
        ["best-practice", "axe-core"],
    ),
    create_rule(
        "landmark-banner-is-top-level",
        "1.3.1",
        "A",
        "Banner landmark should be top level",
        "Ensures banner landmark is at top level. Banner should not be contained in other landmarks.",
        "Perceivable",
        "1.3 Adaptable",
        "semantic",
        ["best-practice", "landmarks", "axe-core"],
    ),
    create_rule(
        "landmark-complementary-is-top-level",
        "1.3.1",
        "A",
        "Complementary landmark should be top level",
        "Ensures complementary landmark is at top level. Aside should not be contained in other landmarks.",
        "Perceivable",
        "1.3 Adaptable",
        "semantic",
        ["best-practice", "landmarks", "axe-core"],
    ),
    create_rule(
        "landmark-contentinfo-is-top-level",
        "1.3.1",
        "A",
        "Contentinfo landmark should be top level",
        "Ensures contentinfo landmark is at top level. Footer should not be contained in other landmarks.",
        "Perceivable",
        "1.3 Adaptable",
        "semantic",
        ["best-practice", "landmarks", "axe-core"],
    ),
    create_rule(
        "landmark-main-is-top-level",
        "1.3.1",
        "A",
        "Main landmark should be top level",
        "Ensures main landmark is at top level. Main should not be contained in other landmarks.",
        "Perceivable",
        "1.3 Adaptable",
        "semantic",
        ["best-practice", "landmarks", "axe-core"],
    ),
    create_rule(
        "landmark-no-duplicate-banner",
        "1.3.1",
        "A",
        "Document should not have more than one banner landmark",
        "Ensures page has no more than one banner landmark. Multiple banners confuse screen reader navigation.",
        "Perceivable",
        "1.3 Adaptable",
        "semantic",
        ["best-practice", "landmarks", "axe-core"],
    ),
    create_rule(
        "landmark-no-duplicate-contentinfo",
        "1.3.1",
        "A",
        "Document should not have more than one contentinfo landmark",
        "Ensures page has no more than one contentinfo landmark. Multiple footers confuse screen reader navigation.",
        "Perceivable",
        "1.3 Adaptable",
        "semantic",
        ["best-practice", "landmarks", "axe-core"],
    ),
    create_rule(
        "landmark-no-duplicate-main",
        "1.3.1",
        "A",
        "Document should not have more than one main landmark",
        "Ensures page has no more than one main landmark. Multiple main landmarks confuse screen reader navigation.",
        "Perceivable",
        "1.3 Adaptable",
        "semantic",
        ["best-practice", "landmarks", "axe-core"],
    ),
    create_rule(
        "page-no-duplicate",
        "2.4.2",
        "A",
        "Page should not have duplicate <html>, <title>, or <main>",
        "Ensures page does not have duplicate critical elements. Duplicate elements create invalid HTML.",
        "Operable",
        "2.4 Navigable",
        "semantic",
        ["best-practice", "axe-core"],
    ),
    create_rule(
        "presentation-role-conflict",
        "4.1.2",
        "A",
        "Elements with role=none or role=presentation should not have global ARIA attributes",
        "Ensures presentation role elements don't have conflicting ARIA. Presentation removes semantics.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["best-practice", "aria", "axe-core"],
    ),
    create_rule(
        "region-missing",
        "1.3.6",
        "AAA",
        "Page should have regions (landmarks) for all content",
        "Ensures all content is contained in landmarks. Landmarks improve screen reader navigation.",
        "Perceivable",
        "1.3 Adaptable",
        "semantic",
        ["best-practice", "landmarks", "axe-core"],
    ),
    create_rule(
        "skip-link",
        "2.4.1",
        "A",
        "Page should have skip link",
        "Ensures page has a skip link (skip to main content). Skip links help keyboard users bypass navigation.",
        "Operable",
        "2.4 Navigable",
        "semantic",
        ["best-practice", "keyboard", "axe-core"],
    ),
    create_rule(
        "table-fake-caption",
        "1.3.1",
        "A",
        "Data tables should use <caption> instead of <p> or other elements",
        "Ensures data tables use proper caption element. Fake captions are not announced correctly.",
        "Perceivable",
        "1.3 Adaptable",
        "semantic",
        ["best-practice", "tables", "axe-core"],
    ),
    create_rule(
        "tabindex-negative",
        "2.4.3",
        "A",
        "tabindex=-1 should not be used on elements that should be focusable",
        "Ensures tabindex=-1 is only used on elements that should be removed from tab order. Negative tabindex can break keyboard navigation.",
        "Operable",
        "2.4 Navigable",
        "general",
        ["best-practice", "keyboard", "axe-core"],
    ),
    create_rule(
        "bypass",
        "2.4.1",
        "A",
        "Page should have method to bypass repeated content",
        "Ensures page has way to skip repeated content (skip link, ARIA landmarks, or headings). Helps keyboard users navigate efficiently.",
        "Operable",
        "2.4 Navigable",
        "semantic",
        ["wcag2a", "wcag241", "section508", "axe-core"],
    ),
    # Experimental Rules (may change in future axe-core versions)
    create_rule(
        "aria-allowed-role",
        "4.1.2",
        "A",
        "ARIA role should be allowed on element (experimental)",
        "Ensures role attribute is allowed on element. Some roles are not valid for certain elements.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["experimental", "aria", "axe-core"],
    ),
    create_rule(
        "empty-table-header",
        "1.3.1",
        "A",
        "Table header cells should not be empty (experimental)",
        "Ensures table headers have content. Empty headers confuse screen reader users.",
        "Perceivable",
        "1.3 Adaptable",
        "semantic",
        ["experimental", "tables", "axe-core"],
    ),
    create_rule(
        "focus-visible",
        "2.4.7",
        "AA",
        "Elements should have visible focus indicator (experimental)",
        "Ensures focusable elements have visible focus indicator. Keyboard users need to see focus location.",
        "Operable",
        "2.4 Navigable",
        "general",
        ["experimental", "wcag2aa", "wcag247", "keyboard", "axe-core"],
    ),
    create_rule(
        "identical-links-different-text",
        "2.4.4",
        "A",
        "Links to the same URL should have same text (experimental)",
        "Ensures links to identical URLs have consistent text. Inconsistent link text confuses users.",
        "Operable",
        "2.4 Navigable",
        "semantic",
        ["experimental", "wcag2a", "wcag244", "axe-core"],
    ),
    create_rule(
        "label-hidden",
        "4.1.2",
        "A",
        "Form labels should not be hidden (experimental)",
        "Ensures form labels are not hidden with display:none or visibility:hidden. Hidden labels prevent form completion.",
        "Robust",
        "4.1 Compatible",
        "form",
        ["experimental", "wcag2a", "wcag412", "forms", "axe-core"],
    ),
    create_rule(
        "p-as-heading",
        "1.3.1",
        "A",
        "Paragraphs should not be styled as headings (experimental)",
        "Ensures <p> elements are not styled to look like headings. Use proper heading elements.",
        "Perceivable",
        "1.3 Adaptable",
        "semantic",
        ["experimental", "wcag2a", "wcag131", "axe-core"],
    ),
    create_rule(
        "table-caption-faked",
        "1.3.1",
        "A",
        "Tables should not use faked captions (experimental)",
        "Ensures tables use proper <caption> element. Screen readers announce captions differently than normal text.",
        "Perceivable",
        "1.3 Adaptable",
        "semantic",
        ["experimental", "wcag2a", "wcag131", "tables", "axe-core"],
    ),
    # Deprecated Rules (kept for backwards compatibility)
    create_rule(
        "aria-dpub-role-fallback",
        "4.1.2",
        "A",
        "ARIA DPUB roles should have fallback (deprecated)",
        "Deprecated: DPUB-ARIA roles should have fallback roles. No longer required in ARIA 1.3+.",
        "Robust",
        "4.1 Compatible",
        "aria",
        ["deprecated", "aria", "axe-core"],
    ),
    create_rule(
        "checkboxgroup",
        "1.3.1",
        "A",
        "Checkbox groups should have fieldset/legend (deprecated)",
        "Deprecated: Use label or label-title-only rule instead. Checkboxes need labels.",
        "Perceivable",
        "1.3 Adaptable",
        "form",
        ["deprecated", "wcag2a", "wcag131", "forms", "axe-core"],
    ),
    create_rule(
        "radiogroup",
        "1.3.1",
        "A",
        "Radio button groups should have fieldset/legend (deprecated)",
        "Deprecated: Use label or label-title-only rule instead. Radio buttons need labels.",
        "Perceivable",
        "1.3 Adaptable",
        "form",
        ["deprecated", "wcag2a", "wcag131", "forms", "axe-core"],
    ),
    create_rule(
        "video-description",
        "1.2.5",
        "AA",
        "Video elements should have audio descriptions (deprecated)",
        "Deprecated: Difficult to automatically test. Videos with visual content should have audio descriptions for blind users.",
        "Perceivable",
        "1.2 Time-based Media",
        "media",
        ["deprecated", "wcag2aa", "wcag125", "axe-core"],
    ),
]

# Combine all rules
ALL_WCAG_GUIDELINES = DETAILED_RULES + EXTENDED_WCAG_GUIDELINES + ADDITIONAL_WCAG_RULES

# Print summary
print(f"Total WCAG Guidelines: {len(ALL_WCAG_GUIDELINES)}")
print(f"  - Detailed rules: {len(DETAILED_RULES)}")
print(f"  - Extended rules: {len(EXTENDED_WCAG_GUIDELINES)}")
print(f"  - Additional rules: {len(ADDITIONAL_WCAG_RULES)}")
