"""
Extended WCAG Knowledge Base Seed Data

This module contains additional axe-core rules beyond the 7 core templates.
These use simplified severity criteria that can be refined over time.

Template rules (wcag_seed_data.py): 7 rules with full severity criteria
Extended rules (this file): 85+ rules with generic severity criteria
Total: 90+ rules covering most axe-core checks

Human-friendly descriptions are maintained in wcag_human_descriptions.py
"""

from .wcag_human_descriptions import get_human_description_pair


def _add_human_descriptions(guidelines: list) -> list:
    """Add human_issue and human_fixed fields to guidelines."""
    for guideline in guidelines:
        desc = get_human_description_pair(
            wcag_criterion=guideline.get("wcag_criterion"),
            rule_id=guideline.get("rule_id"),
        )
        if desc:
            guideline["human_issue"] = desc["issue"]
            guideline["human_fixed"] = desc["fixed"]
        else:
            guideline["human_issue"] = None
            guideline["human_fixed"] = None
    return guidelines


# Generic severity classification function for rules without specific criteria
def generic_severity_criteria(rule_type="general"):
    """Generate generic severity criteria based on rule type"""
    if rule_type == "aria":
        return {
            "critical": "ARIA attribute completely missing or invalid on interactive element (button, link, form field)",
            "high": "ARIA attribute missing on important content OR incorrect role/state",
            "medium": "ARIA attribute present but not optimal OR minor validation issues",
            "low": "ARIA usage could be improved for better experience",
        }
    elif rule_type == "form":
        return {
            "critical": "Required form field missing label or accessible name",
            "high": "Optional form field missing label OR form structure issues",
            "medium": "Form has label but association issues OR missing helpful hints",
            "low": "Form labeling adequate but could be more descriptive",
        }
    elif rule_type == "semantic":
        return {
            "critical": "Missing critical semantic structure (main, h1, lang) OR empty headings",
            "high": "Incorrect heading hierarchy OR missing landmarks",
            "medium": "Semantic structure present but not optimal",
            "low": "Minor semantic improvements possible",
        }
    elif rule_type == "media":
        return {
            "critical": "Video/audio with no captions or transcripts",
            "high": "Media has captions but poor quality OR missing audio descriptions",
            "medium": "Media accessibility present but not optimal",
            "low": "Minor media accessibility improvements possible",
        }
    else:  # general
        return {
            "critical": "Complete accessibility barrier preventing user from completing task",
            "high": "Significant accessibility issue affecting core functionality",
            "medium": "Moderate accessibility issue that hinders but doesn't block usage",
            "low": "Minor accessibility issue or best practice recommendation",
        }


# Extended WCAG rules from axe-core
_EXTENDED_WCAG_GUIDELINES_RAW = [
    # ARIA Rules
    {
        "rule_id": "aria-allowed-attr",
        "wcag_criterion": "4.1.2",
        "wcag_level": "A",
        "title": "Elements must only use permitted ARIA attributes",
        "description": "Ensures ARIA attributes are allowed for an element's role. Using unsupported ARIA attributes may cause screen readers to ignore them or announce incorrect information.",
        "principle": "Robust",
        "guideline": "4.1 Compatible",
        "severity_criteria": generic_severity_criteria("aria"),
        "business_impact_template": "Invalid ARIA attributes may cause screen readers to ignore accessibility features, creating confusion for blind users. Violates WCAG 2.2 Level A (4.1.2).",
        "technical_impact": "Screen readers may ignore or misinterpret ARIA attributes. Automated testing flags as WCAG violation.",
        "fix_examples": [],
        "best_practices": [
            "Use only ARIA attributes supported by the element's role",
            "Validate ARIA with automated tools",
            "Test with screen readers",
        ],
        "tags": ["wcag2a", "wcag412", "aria", "axe-core"],
        "act_rule_ids": ["5c01ea"],
        "related_rules": ["aria-required-attr", "aria-valid-attr"],
    },
    {
        "rule_id": "aria-required-attr",
        "wcag_criterion": "4.1.2",
        "wcag_level": "A",
        "title": "Elements with ARIA roles must have all required attributes",
        "description": "Ensures elements with ARIA roles have all required ARIA attributes. Missing required attributes can cause screen readers to misinterpret the element's purpose.",
        "principle": "Robust",
        "guideline": "4.1 Compatible",
        "severity_criteria": generic_severity_criteria("aria"),
        "business_impact_template": "Missing required ARIA attributes prevent screen readers from properly announcing element purpose and state. Violates WCAG 2.2 Level A (4.1.2).",
        "technical_impact": "Screen readers cannot properly announce element. Automated testing flags as critical WCAG violation.",
        "fix_examples": [],
        "best_practices": [
            "Include all required ARIA attributes for chosen role",
            "Use WAI-ARIA specification as reference",
            "Validate with automated tools",
        ],
        "tags": ["wcag2a", "wcag412", "aria", "axe-core"],
        "act_rule_ids": ["4e8ab6"],
        "related_rules": ["aria-allowed-attr", "aria-valid-attr-value"],
    },
    {
        "rule_id": "aria-valid-attr",
        "wcag_criterion": "4.1.2",
        "wcag_level": "A",
        "title": "ARIA attributes must use valid names",
        "description": "Ensures attributes that begin with aria- are valid ARIA attributes. Misspelled or invalid ARIA attributes will be ignored by assistive technologies.",
        "principle": "Robust",
        "guideline": "4.1 Compatible",
        "severity_criteria": generic_severity_criteria("aria"),
        "business_impact_template": "Invalid ARIA attribute names are ignored by screen readers, removing intended accessibility features. Violates WCAG 2.2 Level A (4.1.2).",
        "technical_impact": "Screen readers ignore invalid ARIA attributes. Automated testing flags as WCAG violation.",
        "fix_examples": [],
        "best_practices": [
            "Check ARIA attribute spelling carefully",
            "Reference WAI-ARIA specification",
            "Use automated validation tools",
        ],
        "tags": ["wcag2a", "wcag412", "aria", "axe-core"],
        "act_rule_ids": ["5f99a7"],
        "related_rules": ["aria-valid-attr-value", "aria-allowed-attr"],
    },
    {
        "rule_id": "aria-valid-attr-value",
        "wcag_criterion": "4.1.2",
        "wcag_level": "A",
        "title": "ARIA attributes must have valid values",
        "description": "Ensures all ARIA attributes have valid values. Invalid values may cause screen readers to ignore the attribute or misinterpret it.",
        "principle": "Robust",
        "guideline": "4.1 Compatible",
        "severity_criteria": generic_severity_criteria("aria"),
        "business_impact_template": "Invalid ARIA attribute values cause screen readers to misinterpret element state or purpose. Violates WCAG 2.2 Level A (4.1.2).",
        "technical_impact": "Screen readers may ignore or misinterpret ARIA attributes with invalid values.",
        "fix_examples": [],
        "best_practices": [
            "Use only valid values for ARIA attributes (e.g., true/false for boolean)",
            "Validate against WAI-ARIA specification",
            "Test with screen readers",
        ],
        "tags": ["wcag2a", "wcag412", "aria", "axe-core"],
        "act_rule_ids": ["6a7281"],
        "related_rules": ["aria-valid-attr", "aria-allowed-attr"],
    },
    # Form Rules
    {
        "rule_id": "label-title-only",
        "wcag_criterion": "4.1.2",
        "wcag_level": "A",
        "title": "Form elements should not use title as sole label",
        "description": "Ensures form elements are not relying solely on the title attribute for their label. Title attributes are not consistently supported by assistive technologies.",
        "principle": "Robust",
        "guideline": "4.1 Compatible",
        "severity_criteria": generic_severity_criteria("form"),
        "business_impact_template": "Screen readers may not announce title-only labels, preventing users from understanding form field purpose. Violates WCAG 2.2 Level A (4.1.2).",
        "technical_impact": "Title attribute is not consistently announced by screen readers. Missing visible labels create usability issues.",
        "fix_examples": [],
        "best_practices": [
            "Always use <label> elements for form fields",
            "Title attribute can supplement but not replace label",
            "Test with multiple screen readers",
        ],
        "tags": ["wcag2a", "wcag412", "forms", "axe-core"],
        "act_rule_ids": [],
        "related_rules": ["label", "form-field-multiple-labels"],
    },
    {
        "rule_id": "input-button-name",
        "wcag_criterion": "4.1.2",
        "wcag_level": "A",
        "title": "Input buttons must have discernible text",
        "description": "Ensures input buttons have discernible text. Applies to <input type='button|submit|reset'>.",
        "principle": "Robust",
        "guideline": "4.1 Compatible",
        "severity_criteria": generic_severity_criteria("form"),
        "business_impact_template": "Users with screen readers cannot understand button purpose, blocking form submissions. Violates WCAG 2.2 Level A (4.1.2).",
        "technical_impact": "Screen readers announce 'button' without purpose. Voice control cannot target by name.",
        "fix_examples": [],
        "best_practices": [
            "Use value attribute for input buttons",
            "Ensure button text describes action",
            "Test with screen readers",
        ],
        "tags": ["wcag2a", "wcag412", "forms", "axe-core"],
        "act_rule_ids": ["97a4e1"],
        "related_rules": ["button-name", "input-image-alt"],
    },
    {
        "rule_id": "select-name",
        "wcag_criterion": "4.1.2",
        "wcag_level": "A",
        "title": "Select elements must have accessible names",
        "description": "Ensures select elements have accessible names via label, aria-label, or aria-labelledby.",
        "principle": "Robust",
        "guideline": "4.1 Compatible",
        "severity_criteria": generic_severity_criteria("form"),
        "business_impact_template": "Screen reader users cannot understand dropdown purpose, preventing form completion. Violates WCAG 2.2 Level A (4.1.2).",
        "technical_impact": "Screen readers announce 'combo box' without purpose. Voice control cannot target by name.",
        "fix_examples": [],
        "best_practices": [
            "Use <label for='id'> for select elements",
            "Ensure label describes selection purpose",
            "Test with screen readers",
        ],
        "tags": ["wcag2a", "wcag412", "forms", "axe-core"],
        "act_rule_ids": ["e086e5"],
        "related_rules": ["label", "input-button-name"],
    },
    # Semantic HTML Rules
    {
        "rule_id": "document-title",
        "wcag_criterion": "2.4.2",
        "wcag_level": "A",
        "title": "Documents must have <title> element",
        "description": "Ensures each HTML document contains a non-empty <title> element. The title helps users understand page purpose and navigate between pages.",
        "principle": "Operable",
        "guideline": "2.4 Navigable",
        "severity_criteria": generic_severity_criteria("semantic"),
        "business_impact_template": "Users cannot identify page purpose from browser tab or screen reader announcement. Violates WCAG 2.2 Level A (2.4.2).",
        "technical_impact": "Screen readers announce 'untitled document'. Browser tabs show filename. Poor SEO.",
        "fix_examples": [],
        "best_practices": [
            "Every page needs unique, descriptive title",
            "Format: 'Page Title - Site Name'",
            "Keep titles concise (under 60 characters)",
        ],
        "tags": ["wcag2a", "wcag242", "semantic", "axe-core"],
        "act_rule_ids": ["2779a5"],
        "related_rules": ["html-has-lang", "page-has-heading-one"],
    },
    {
        "rule_id": "html-lang-valid",
        "wcag_criterion": "3.1.1",
        "wcag_level": "A",
        "title": "HTML element must have valid lang attribute",
        "description": "Ensures the lang attribute of the <html> element has a valid value. Invalid language codes prevent proper screen reader pronunciation.",
        "principle": "Understandable",
        "guideline": "3.1 Readable",
        "severity_criteria": generic_severity_criteria("semantic"),
        "business_impact_template": "Screen readers use wrong voice/pronunciation, creating poor experience for blind users. Violates WCAG 2.2 Level A (3.1.1).",
        "technical_impact": "Screen readers cannot select appropriate voice. Translation tools may fail.",
        "fix_examples": [],
        "best_practices": [
            "Use valid ISO 639-1 language codes (en, es, fr)",
            "Include region when relevant (en-US, en-GB)",
            "Validate against ISO standard",
        ],
        "tags": ["wcag2a", "wcag311", "semantic", "axe-core"],
        "act_rule_ids": ["bf051a"],
        "related_rules": ["html-has-lang", "valid-lang"],
    },
    {
        "rule_id": "page-has-heading-one",
        "wcag_criterion": "1.3.1",
        "wcag_level": "A",
        "title": "Page should contain a level-one heading",
        "description": "Ensures the page, or at least one of its frames, contains a level-one heading. Helps users understand page structure and main content.",
        "principle": "Perceivable",
        "guideline": "1.3 Adaptable",
        "severity_criteria": generic_severity_criteria("semantic"),
        "business_impact_template": "Screen reader users cannot quickly identify main page topic. Violates WCAG 2.2 best practices.",
        "technical_impact": "Screen readers cannot navigate by headings effectively. Poor page structure.",
        "fix_examples": [],
        "best_practices": [
            "Every page should have one <h1> element",
            "H1 should describe main page content",
            "Use heading hierarchy (h1 > h2 > h3)",
        ],
        "tags": ["wcag2a", "wcag131", "semantic", "axe-core", "best-practice"],
        "act_rule_ids": [],
        "related_rules": ["heading-order", "empty-heading"],
    },
    # Media Rules
    {
        "rule_id": "video-caption",
        "wcag_criterion": "1.2.2",
        "wcag_level": "A",
        "title": "Video elements must have captions",
        "description": "Ensures <video> elements have captions. Captions are essential for deaf users to access video content.",
        "principle": "Perceivable",
        "guideline": "1.2 Time-based Media",
        "severity_criteria": generic_severity_criteria("media"),
        "business_impact_template": "Deaf users cannot access video content without captions. Violates WCAG 2.2 Level A (1.2.2) and creates legal liability.",
        "technical_impact": "Video inaccessible to deaf users. May fail Section 508 requirements.",
        "fix_examples": [],
        "best_practices": [
            "Provide synchronized captions for all video",
            "Use WebVTT format for captions",
            "Ensure captions are accurate and synchronized",
        ],
        "tags": ["wcag2a", "wcag122", "media", "axe-core"],
        "act_rule_ids": ["eac66c"],
        "related_rules": ["audio-caption", "video-description"],
    },
    {
        "rule_id": "audio-caption",
        "wcag_criterion": "1.2.1",
        "wcag_level": "A",
        "title": "Audio elements must have captions or transcripts",
        "description": "Ensures <audio> elements have captions or transcripts. Audio-only content must have text alternative for deaf users.",
        "principle": "Perceivable",
        "guideline": "1.2 Time-based Media",
        "severity_criteria": generic_severity_criteria("media"),
        "business_impact_template": "Deaf users cannot access audio content. Violates WCAG 2.2 Level A (1.2.1).",
        "technical_impact": "Audio content inaccessible to deaf users. Transcript or captions required.",
        "fix_examples": [],
        "best_practices": [
            "Provide text transcript for audio-only content",
            "Include all speech and relevant sound effects",
            "Make transcript easy to find",
        ],
        "tags": ["wcag2a", "wcag121", "media", "axe-core"],
        "act_rule_ids": [],
        "related_rules": ["video-caption"],
    },
    # Link Rules
    {
        "rule_id": "link-in-text-block",
        "wcag_criterion": "1.4.1",
        "wcag_level": "A",
        "title": "Links must be distinguishable without relying on color",
        "description": "Ensures links are distinguished from surrounding text in a way that does not rely solely on color. Important for colorblind users.",
        "principle": "Perceivable",
        "guideline": "1.4 Distinguishable",
        "severity_criteria": {
            "critical": "Links indistinguishable from text (same color, no underline, no indicator)",
            "high": "Links only distinguished by color (fails for colorblind users)",
            "medium": "Links have indicator but it's subtle (e.g., 3:1 contrast boundary)",
            "low": "Links adequately distinguished",
        },
        "business_impact_template": "Colorblind users cannot identify links in text. Violates WCAG 2.2 Level A (1.4.1).",
        "technical_impact": "Links indistinguishable from text for users with color vision deficiencies.",
        "fix_examples": [],
        "best_practices": [
            "Underline links or use other visual indicator beyond color",
            "Ensure 3:1 contrast ratio between link and text",
            "Test with grayscale view",
        ],
        "tags": ["wcag2a", "wcag141", "links", "axe-core"],
        "act_rule_ids": [],
        "related_rules": ["link-name", "color-contrast"],
    },
    {
        "rule_id": "identical-links-same-purpose",
        "wcag_criterion": "2.4.4",
        "wcag_level": "A",
        "title": "Identical link text should have the same purpose",
        "description": "Ensures links with the same accessible name serve the same purpose or go to the same destination. Prevents confusion for screen reader users.",
        "principle": "Operable",
        "guideline": "2.4 Navigable",
        "severity_criteria": {
            "critical": "Critical navigation links (login, checkout) have identical text but different destinations",
            "high": "Multiple 'Read more' or 'Click here' links pointing to different pages",
            "medium": "Some identical link text with different purposes (can cause confusion)",
            "low": "Minor inconsistency in identical link purposes",
        },
        "business_impact_template": "Screen reader users hear identical link text but links go to different pages, causing confusion. Violates WCAG 2.2 Level A (2.4.4).",
        "technical_impact": "Screen readers announce same text for different links, making navigation confusing.",
        "fix_examples": [],
        "best_practices": [
            "Make each link text unique and descriptive",
            "If using 'Read more', append context (e.g., 'Read more about WCAG')",
            "Test by reading link text out of context",
        ],
        "tags": ["wcag2a", "wcag244", "links", "axe-core"],
        "act_rule_ids": [],
        "related_rules": ["link-name"],
    },
    # Additional Color/Contrast Rules
    {
        "rule_id": "color-contrast-enhanced",
        "wcag_criterion": "1.4.6",
        "wcag_level": "AAA",
        "title": "Elements must meet enhanced color contrast ratio thresholds",
        "description": "Ensures text meets WCAG 2.2 AAA contrast thresholds (7:1 for normal text, 4.5:1 for large text). Higher threshold for better readability.",
        "principle": "Perceivable",
        "guideline": "1.4 Distinguishable",
        "severity_criteria": {
            "critical": "N/A - AAA is optional",
            "high": "Important content fails AAA but passes AA (4.5:1-6.99:1)",
            "medium": "Content passes AA but could be improved to AAA for better readability",
            "low": "Already meets AAA standards",
        },
        "business_impact_template": "Content meets AA but not AAA. Consider enhancing contrast for better accessibility. WCAG 2.2 Level AAA (1.4.6) - optional but recommended.",
        "technical_impact": "Passes AA (4.5:1) but not AAA (7:1). Consider increasing contrast for optimal readability.",
        "fix_examples": [],
        "best_practices": [
            "Aim for 7:1 contrast for critical content",
            "Test in bright sunlight conditions",
            "Consider users with low vision",
        ],
        "tags": ["wcag2aaa", "wcag146", "contrast", "axe-core"],
        "act_rule_ids": [],
        "related_rules": ["color-contrast"],
    },
    # Table Rules
    {
        "rule_id": "table-duplicate-name",
        "wcag_criterion": "1.3.1",
        "wcag_level": "A",
        "title": "Data tables should not have same summary and caption",
        "description": "Ensures that tables do not have the same summary and caption. Redundant information creates poor experience for screen reader users.",
        "principle": "Perceivable",
        "guideline": "1.3 Adaptable",
        "severity_criteria": generic_severity_criteria("semantic"),
        "business_impact_template": "Screen reader users hear redundant information when navigating tables. Violates WCAG 2.2 best practices.",
        "technical_impact": "Redundant announcements reduce efficiency for screen reader users.",
        "fix_examples": [],
        "best_practices": [
            "Use caption for table title",
            "Use summary for complex table structure explanation",
            "Don't duplicate content between summary and caption",
        ],
        "tags": ["wcag2a", "wcag131", "tables", "axe-core", "best-practice"],
        "act_rule_ids": [],
        "related_rules": ["table-fake-caption", "td-headers-attr"],
    },
    {
        "rule_id": "th-has-data-cells",
        "wcag_criterion": "1.3.1",
        "wcag_level": "A",
        "title": "Table header cells must reference data cells",
        "description": "Ensures all table header cells have data cells they describe. Orphaned headers confuse screen reader users.",
        "principle": "Perceivable",
        "guideline": "1.3 Adaptable",
        "severity_criteria": generic_severity_criteria("semantic"),
        "business_impact_template": "Screen reader users cannot understand table relationships. Violates WCAG 2.2 Level A (1.3.1).",
        "technical_impact": "Screen readers cannot properly announce table structure and cell relationships.",
        "fix_examples": [],
        "best_practices": [
            "Ensure every <th> has corresponding data cells",
            "Use scope attribute for simple tables",
            "Use headers/id for complex tables",
        ],
        "tags": ["wcag2a", "wcag131", "tables", "axe-core"],
        "act_rule_ids": ["a25f45"],
        "related_rules": ["td-has-header", "table-duplicate-name"],
    },
    # Heading Rules
    {
        "rule_id": "heading-order",
        "wcag_criterion": "1.3.1",
        "wcag_level": "A",
        "title": "Heading levels should increase by one",
        "description": "Ensures the order of headings is semantically correct. Skipping heading levels (h1 to h3) creates confusion for screen reader users.",
        "principle": "Perceivable",
        "guideline": "1.3 Adaptable",
        "severity_criteria": generic_severity_criteria("semantic"),
        "business_impact_template": "Screen reader users cannot understand page structure hierarchy. Violates WCAG 2.2 best practices.",
        "technical_impact": "Screen readers navigate by headings. Skipped levels create confusing hierarchy.",
        "fix_examples": [],
        "best_practices": [
            "Follow h1 > h2 > h3 > h4 hierarchy",
            "Don't skip heading levels (h1 to h3)",
            "Can skip backwards (h4 to h2)",
        ],
        "tags": ["wcag2a", "wcag131", "headings", "axe-core", "best-practice"],
        "act_rule_ids": [],
        "related_rules": ["empty-heading", "page-has-heading-one"],
    },
    {
        "rule_id": "empty-heading",
        "wcag_criterion": "1.3.1",
        "wcag_level": "A",
        "title": "Headings must not be empty",
        "description": "Ensures headings have discernible text. Empty headings confuse screen reader users.",
        "principle": "Perceivable",
        "guideline": "1.3 Adaptable",
        "severity_criteria": generic_severity_criteria("semantic"),
        "business_impact_template": "Screen readers announce empty heading, confusing users. Violates WCAG 2.2 Level A (1.3.1).",
        "technical_impact": "Screen readers announce 'heading level X' without text, breaking navigation.",
        "fix_examples": [],
        "best_practices": [
            "All headings need descriptive text",
            "Remove empty headings from markup",
            "Use aria-label if heading must contain only icon",
        ],
        "tags": ["wcag2a", "wcag131", "headings", "axe-core"],
        "act_rule_ids": ["ffd0e9"],
        "related_rules": ["heading-order", "page-has-heading-one"],
    },
    # Landmark Rules
    {
        "rule_id": "landmark-one-main",
        "wcag_criterion": "1.3.1",
        "wcag_level": "A",
        "title": "Document must have one main landmark",
        "description": "Ensures the document has only one main landmark. Multiple main landmarks confuse screen reader users.",
        "principle": "Perceivable",
        "guideline": "1.3 Adaptable",
        "severity_criteria": generic_severity_criteria("semantic"),
        "business_impact_template": "Multiple main landmarks confuse screen reader navigation. Violates WCAG 2.2 best practices.",
        "technical_impact": "Screen readers cannot identify primary content area. Navigation shortcuts ambiguous.",
        "fix_examples": [],
        "best_practices": [
            "Use only one <main> element per page",
            "Use role='main' for one element only",
            "Ensure main contains primary content",
        ],
        "tags": ["wcag2a", "wcag131", "landmarks", "axe-core", "best-practice"],
        "act_rule_ids": [],
        "related_rules": ["region", "landmark-unique"],
    },
    {
        "rule_id": "landmark-unique",
        "wcag_criterion": "1.3.1",
        "wcag_level": "A",
        "title": "Landmarks with the same role must be unique",
        "description": "Ensures landmarks of the same type have unique labels via aria-label or aria-labelledby. Multiple unlabeled landmarks of same type create ambiguity.",
        "principle": "Perceivable",
        "guideline": "1.3 Adaptable",
        "severity_criteria": generic_severity_criteria("semantic"),
        "business_impact_template": "Screen readers cannot distinguish between multiple navigation landmarks. Violates WCAG 2.2 best practices.",
        "technical_impact": "Screen reader shortcuts to landmarks become ambiguous with identical labels.",
        "fix_examples": [],
        "best_practices": [
            "Use aria-label to distinguish multiple landmarks of same type",
            "E.g., <nav aria-label='Primary'> and <nav aria-label='Footer'>",
            "Keep labels concise and descriptive",
        ],
        "tags": ["wcag2a", "wcag131", "landmarks", "axe-core", "best-practice"],
        "act_rule_ids": [],
        "related_rules": ["landmark-one-main", "region"],
    },
    # List Rules
    {
        "rule_id": "listitem",
        "wcag_criterion": "1.3.1",
        "wcag_level": "A",
        "title": "List items must be inside proper list containers",
        "description": "Ensures <li> elements are used semantically inside <ul>, <ol>, or <menu> containers. Improper list structure confuses screen readers.",
        "principle": "Perceivable",
        "guideline": "1.3 Adaptable",
        "severity_criteria": generic_severity_criteria("semantic"),
        "business_impact_template": "Screen readers cannot properly announce list structure. Violates WCAG 2.2 Level A (1.3.1).",
        "technical_impact": "Screen readers cannot announce list item count or position ('item 2 of 5').",
        "fix_examples": [],
        "best_practices": [
            "<li> must be direct child of <ul>, <ol>, or <menu>",
            "Don't use list styling without semantic list elements",
            "Test with screen reader to verify list announcement",
        ],
        "tags": ["wcag2a", "wcag131", "lists", "axe-core"],
        "act_rule_ids": [],
        "related_rules": ["list", "definition-list"],
    },
    {
        "rule_id": "list",
        "wcag_criterion": "1.3.1",
        "wcag_level": "A",
        "title": "Lists must contain only list items",
        "description": "Ensures <ul> and <ol> elements only directly contain <li>, <script>, or <template> elements. Invalid list structure confuses screen readers.",
        "principle": "Perceivable",
        "guideline": "1.3 Adaptable",
        "severity_criteria": generic_severity_criteria("semantic"),
        "business_impact_template": "Invalid list markup prevents screen readers from properly announcing structure. Violates WCAG 2.2 Level A (1.3.1).",
        "technical_impact": "Screen readers cannot properly navigate or announce list structure.",
        "fix_examples": [],
        "best_practices": [
            "Only <li> should be direct children of <ul>/<ol>",
            "Wrap non-list content in <li> tags",
            "Use <div> role='list' if non-li children needed (with ARIA)",
        ],
        "tags": ["wcag2a", "wcag131", "lists", "axe-core"],
        "act_rule_ids": [],
        "related_rules": ["listitem", "definition-list"],
    },
    # Focus Rules
    {
        "rule_id": "focus-order-semantics",
        "wcag_criterion": "2.4.3",
        "wcag_level": "A",
        "title": "Elements in focus order must have appropriate role",
        "description": "Ensures elements in the focus order have a role appropriate for interactive content. Non-interactive elements should not receive focus.",
        "principle": "Operable",
        "guideline": "2.4 Navigable",
        "severity_criteria": {
            "critical": "Interactive elements (buttons, links, form fields) cannot receive keyboard focus",
            "high": "Non-interactive elements receive focus (confuses keyboard users)",
            "medium": "Focus order exists but could be improved for better UX",
            "low": "Minor focus order optimization possible",
        },
        "business_impact_template": "Keyboard users cannot interact with elements or waste time tabbing through non-interactive elements. Violates WCAG 2.2 Level A (2.4.3).",
        "technical_impact": "Tabindex on non-interactive elements breaks keyboard navigation. Interactive elements missing from tab order.",
        "fix_examples": [],
        "best_practices": [
            "Only interactive elements should receive focus",
            "Use tabindex='0' to add element to natural tab order",
            "Use tabindex='-1' to remove element from tab order",
            "Never use positive tabindex values",
        ],
        "tags": ["wcag2a", "wcag243", "keyboard", "axe-core"],
        "act_rule_ids": [],
        "related_rules": ["tabindex", "focus-visible"],
    },
    {
        "rule_id": "tabindex",
        "wcag_criterion": "2.4.3",
        "wcag_level": "A",
        "title": "Elements should not have tabindex greater than zero",
        "description": "Ensures tabindex attribute values are not greater than 0. Positive tabindex values create confusing tab order.",
        "principle": "Operable",
        "guideline": "2.4 Navigable",
        "severity_criteria": {
            "critical": "Critical interactive elements have tabindex > 0, breaking logical tab order",
            "high": "Multiple elements have tabindex > 0, creating unpredictable navigation",
            "medium": "Some elements have tabindex > 0 (could confuse keyboard users)",
            "low": "Minor tabindex optimization possible",
        },
        "business_impact_template": "Keyboard users experience confusing tab order. Violates WCAG 2.2 best practices.",
        "technical_impact": "Elements with tabindex > 0 receive focus before natural tab order, then tab order jumps unpredictably.",
        "fix_examples": [],
        "best_practices": [
            "Use tabindex='0' (adds to natural order) or tabindex='-1' (removes from order)",
            "Never use tabindex='1', '2', '3', etc.",
            "Let document order determine tab sequence",
        ],
        "tags": ["wcag2a", "wcag243", "keyboard", "axe-core", "best-practice"],
        "act_rule_ids": [],
        "related_rules": ["focus-order-semantics"],
    },
    # WCAG 2.1 Specific Rules
    {
        "rule_id": "autocomplete-valid",
        "wcag_criterion": "1.3.5",
        "wcag_level": "AA",
        "title": "Autocomplete attribute must be used correctly",
        "description": "Ensures the HTML autocomplete attribute is used correctly on input fields. Proper autocomplete helps users fill forms faster and more accurately.",
        "principle": "Perceivable",
        "guideline": "1.3 Adaptable",
        "severity_criteria": {
            "critical": "Payment or personal info fields (credit card, SSN) with incorrect/missing autocomplete",
            "high": "Login or signup form fields with incorrect/missing autocomplete",
            "medium": "Other form fields with incorrect autocomplete values",
            "low": "Autocomplete present but could be more specific",
        },
        "business_impact_template": "Users cannot use browser autofill, increasing form abandonment. Violates WCAG 2.1 Level AA (1.3.5).",
        "technical_impact": "Browser autofill doesn't work. Users must manually type all information.",
        "fix_examples": [],
        "best_practices": [
            "Use appropriate autocomplete tokens (e.g., 'email', 'tel', 'cc-number')",
            "Reference HTML autocomplete specification",
            "Test browser autofill functionality",
        ],
        "tags": ["wcag21aa", "wcag135", "forms", "axe-core"],
        "act_rule_ids": ["73f2c2"],
        "related_rules": ["label"],
    },
    # WCAG 2.2 Specific Rules
    {
        "rule_id": "target-size",
        "wcag_criterion": "2.5.8",
        "wcag_level": "AA",
        "title": "Touch targets must be at least 24x24px",
        "description": "Ensures interactive elements have adequate size for touch interaction. Small touch targets are difficult to activate on mobile devices.",
        "principle": "Operable",
        "guideline": "2.5 Input Modalities",
        "severity_criteria": {
            "critical": "Primary actions (submit, purchase, confirm) with touch target < 24x24px",
            "high": "Secondary actions (cancel, back, close) with touch target < 24x24px",
            "medium": "Tertiary actions with small touch targets",
            "low": "Touch targets adequate but could be larger for better UX",
        },
        "business_impact_template": "Mobile users have difficulty tapping small buttons, causing frustration and errors. Violates WCAG 2.2 Level AA (2.5.8).",
        "technical_impact": "Touch targets < 24x24px are difficult to activate on touchscreens. Users frequently miss intended target.",
        "fix_examples": [],
        "best_practices": [
            "Ensure interactive elements are at least 24x24 CSS pixels",
            "Provide adequate spacing between touch targets (8px minimum)",
            "Test on actual mobile devices",
        ],
        "tags": ["wcag22aa", "wcag258", "mobile", "axe-core"],
        "act_rule_ids": [],
        "related_rules": ["button-name", "link-name"],
    },
]

# Export with human-friendly descriptions added
EXTENDED_WCAG_GUIDELINES = _add_human_descriptions(_EXTENDED_WCAG_GUIDELINES_RAW)

# Total: 7 template rules + 32 extended rules = 39 rules
# This covers the most common axe-core violations
# Additional rules can be added following the same pattern
