#!/usr/bin/env python3
"""Verify that runtime environment reads and ``.env.example`` stay in parity."""

from __future__ import annotations

import argparse
import ast
from dataclasses import dataclass
import ipaddress
from pathlib import Path
import re
from urllib.parse import urlsplit

REPO_ROOT = Path(__file__).resolve().parents[1]

LEGACY_ENVIRONMENT_ALIASES = {
    "API_BASE_URL": "PUBLIC_API_URL",
    "BASE_URL": "PUBLIC_API_URL",
    "ENVIRONMENT": "ENV",
    "OLLAMA_FALLBACK_CODE": "OLLAMA_CODE_MODEL",
    "OLLAMA_FALLBACK_TEXT": "OLLAMA_TEXT_MODEL",
    "OLLAMA_FALLBACK_VISION": "OLLAMA_VISION_MODEL",
}

INTERNAL_ENVIRONMENT_NAMES = {
    "API_KEY_HEADER": "fixed HTTP protocol metadata, not operator configuration",
    "API_KEY_PREFIX": "fixed HTTP protocol metadata, not operator configuration",
    "API_TITLE": "derived application metadata",
    "API_VERSION": "derived release metadata",
    "CORS_ALLOW_CREDENTIALS": "fixed security policy",
    "CORS_ALLOW_HEADERS": "fixed security policy",
    "CORS_ALLOW_METHODS": "fixed security policy",
    "DEFAULT_RATE_LIMIT_PER_HOUR": "internal application default",
    "JOB_WORKER_ID": "ephemeral worker identity generated by the worker process",
    "MAX_FILE_SIZE_CODE": "internal byte limit without an environment contract",
    "MAX_FILE_SIZE_IMAGE": "internal byte limit without an environment contract",
    "MAX_FILE_SIZE_PDF": "internal byte limit without an environment contract",
    "MAX_FILE_SIZE_PPTX": "internal byte limit without an environment contract",
    "MAX_FILE_SIZE_VIDEO": "internal byte limit without an environment contract",
    "MAX_IMAGE_PIXELS": "internal image safety limit",
    "REQUEST_TIMEOUT": "internal request deadline",
    "TESSDATA_PREFIX": "runtime owned by the system Tesseract installation",
}

TEMPLATE_ONLY_ENVIRONMENT_NAMES = {
    "POSTGRES_DB": "consumed by the supplied Docker Compose deployment",
    "POSTGRES_PASSWORD": "consumed by the supplied Docker Compose deployment",
    "POSTGRES_USER": "consumed by the supplied Docker Compose deployment",
}

_PROVIDER_NAMES = ("ANTHROPIC", "GEMINI", "OLLAMA", "OPENAI", "XAI")
_DYNAMIC_ENVIRONMENT_NAMES = {
    ("src/ai/providers/manager.py", "ProviderRateLimiter._load_limits", "rpm_key"): {
        f"{provider}_RATE_LIMIT_RPM" for provider in _PROVIDER_NAMES
    },
    ("src/ai/providers/manager.py", "ProviderRateLimiter._load_limits", "rpd_key"): {
        f"{provider}_RATE_LIMIT_RPD" for provider in _PROVIDER_NAMES
    },
    ("src/ai/providers/manager.py", "ProviderManager._get_env_provider", "env_var"): {
        "LLM_FALLBACK_PROVIDER",
        "LLM_PROVIDER",
    },
    (
        "src/ai/providers/manager.py",
        "ProviderManager._model_from_environment",
        "name",
    ): {
        "OLLAMA_CODE_MODEL",
        "OLLAMA_TEXT_MODEL",
        "OLLAMA_VISION_MODEL",
    },
    (
        "src/ai/providers/manager.py",
        "ProviderManager._model_from_environment",
        "legacy_name",
    ): {
        "OLLAMA_FALLBACK_CODE",
        "OLLAMA_FALLBACK_TEXT",
        "OLLAMA_FALLBACK_VISION",
    },
}

_ENV_DECLARATION = re.compile(r"^\s*#?\s*([A-Z][A-Z0-9_]*)=(.*)$")
_SECRET_NAME = re.compile(r"(?:API_KEY|ENCRYPTION_KEY|PASSWORD|SECRET|TOKEN)$")
_SAFE_SECRET_MARKERS = (
    "change-me",
    "generate",
    "localhost",
    "username:password",
    "your-",
)


@dataclass(frozen=True)
class EnvironmentAccess:
    name: str
    source: str
    line: int


@dataclass(frozen=True)
class DynamicEnvironmentAccess:
    source: str
    scope: str
    expression: str
    line: int

    @property
    def classification_key(self) -> tuple[str, str, str]:
        return (self.source, self.scope, self.expression)


@dataclass(frozen=True)
class EnvironmentExampleEntry:
    name: str
    value: str
    commented: bool
    line: int


class _EnvironmentVisitor(ast.NodeVisitor):
    def __init__(self, source: str, module_constants: dict[str, str]) -> None:
        self.source = source
        self.module_constants = module_constants
        self.scope: list[str] = []
        self.accesses: list[EnvironmentAccess] = []
        self.dynamic_accesses: list[DynamicEnvironmentAccess] = []

    def visit_ClassDef(self, node: ast.ClassDef) -> None:
        self.scope.append(node.name)
        self.generic_visit(node)
        self.scope.pop()

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        self.scope.append(node.name)
        self.generic_visit(node)
        self.scope.pop()

    visit_AsyncFunctionDef = visit_FunctionDef

    def visit_Call(self, node: ast.Call) -> None:
        if self._is_environment_getter(node.func) and node.args:
            self._record_key(node.args[0], node.lineno)
        self.generic_visit(node)

    def visit_Subscript(self, node: ast.Subscript) -> None:
        if self._is_os_environ(node.value):
            self._record_key(node.slice, node.lineno)
        self.generic_visit(node)

    @staticmethod
    def _is_os_environ(node: ast.AST) -> bool:
        return (
            isinstance(node, ast.Attribute)
            and isinstance(node.value, ast.Name)
            and node.value.id == "os"
            and node.attr == "environ"
        )

    @classmethod
    def _is_environment_getter(cls, node: ast.AST) -> bool:
        if not isinstance(node, ast.Attribute):
            return False
        if isinstance(node.value, ast.Name):
            return node.value.id == "os" and node.attr == "getenv"
        return cls._is_os_environ(node.value) and node.attr == "get"

    def _record_key(self, node: ast.AST, line: int) -> None:
        name: str | None = None
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            name = node.value
        elif isinstance(node, ast.Name):
            name = self.module_constants.get(node.id)

        if name is not None:
            self.accesses.append(EnvironmentAccess(name, self.source, line))
            return

        self.dynamic_accesses.append(
            DynamicEnvironmentAccess(
                source=self.source,
                scope=".".join(self.scope) or "<module>",
                expression=ast.unparse(node),
                line=line,
            )
        )


def _module_string_constants(tree: ast.Module) -> dict[str, str]:
    constants: dict[str, str] = {}
    for statement in tree.body:
        if not isinstance(statement, (ast.Assign, ast.AnnAssign)):
            continue
        value = statement.value
        if not isinstance(value, ast.Constant) or not isinstance(value.value, str):
            continue
        targets = (
            statement.targets
            if isinstance(statement, ast.Assign)
            else [statement.target]
        )
        for target in targets:
            if isinstance(target, ast.Name):
                constants[target.id] = value.value
    return constants


def discover_environment_accesses(
    source_root: Path,
) -> tuple[set[str], tuple[DynamicEnvironmentAccess, ...]]:
    accesses: set[str] = set()
    dynamic_accesses: list[DynamicEnvironmentAccess] = []
    repository_root = source_root.parent

    for path in sorted(source_root.rglob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        relative_path = path.relative_to(repository_root).as_posix()
        visitor = _EnvironmentVisitor(relative_path, _module_string_constants(tree))
        visitor.visit(tree)
        accesses.update(access.name for access in visitor.accesses)
        dynamic_accesses.extend(visitor.dynamic_accesses)

    return accesses, tuple(dynamic_accesses)


def _field_aliases(value: ast.AST | None) -> set[str]:
    if not isinstance(value, ast.Call):
        return set()
    aliases: set[str] = set()
    for keyword in value.keywords:
        if keyword.arg not in {"alias", "validation_alias"}:
            continue
        if isinstance(keyword.value, ast.Constant) and isinstance(
            keyword.value.value, str
        ):
            aliases.add(keyword.value.value)
        elif isinstance(keyword.value, ast.Call):
            aliases.update(
                argument.value
                for argument in keyword.value.args
                if isinstance(argument, ast.Constant)
                and isinstance(argument.value, str)
            )
    return aliases


def _class_config(node: ast.ClassDef) -> tuple[str, str | None]:
    env_prefix = ""
    nested_delimiter: str | None = None

    def apply_keywords(call: ast.Call) -> None:
        nonlocal env_prefix, nested_delimiter
        for keyword in call.keywords:
            if not isinstance(keyword.value, ast.Constant) or not isinstance(
                keyword.value.value, str
            ):
                continue
            if keyword.arg == "env_prefix":
                env_prefix = keyword.value.value
            elif keyword.arg == "env_nested_delimiter":
                nested_delimiter = keyword.value.value

    for statement in node.body:
        if isinstance(statement, (ast.Assign, ast.AnnAssign)):
            value = statement.value
            if isinstance(value, ast.Call):
                apply_keywords(value)
        if isinstance(statement, ast.ClassDef) and statement.name == "Config":
            for config_statement in statement.body:
                if not isinstance(config_statement, (ast.Assign, ast.AnnAssign)):
                    continue
                targets = (
                    config_statement.targets
                    if isinstance(config_statement, ast.Assign)
                    else [config_statement.target]
                )
                if not isinstance(config_statement.value, ast.Constant):
                    continue
                for target in targets:
                    if not isinstance(target, ast.Name):
                        continue
                    if target.id == "env_prefix" and isinstance(
                        config_statement.value.value, str
                    ):
                        env_prefix = config_statement.value.value
                    elif target.id == "env_nested_delimiter" and isinstance(
                        config_statement.value.value, str
                    ):
                        nested_delimiter = config_statement.value.value
    return env_prefix, nested_delimiter


def _annotation_names(node: ast.AST | None) -> set[str]:
    if node is None:
        return set()
    return {child.id for child in ast.walk(node) if isinstance(child, ast.Name)}


def _inherits_base_settings(node: ast.ClassDef) -> bool:
    return any(
        (isinstance(base, ast.Name) and base.id == "BaseSettings")
        or (isinstance(base, ast.Attribute) and base.attr == "BaseSettings")
        for base in node.bases
    )


def discover_settings_environment_names(source_root: Path) -> set[str]:
    """Return names accepted by every ``BaseSettings`` field in ``source_root``."""
    classes: dict[str, ast.ClassDef] = {}
    for path in sorted(source_root.rglob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        classes.update(
            {node.name: node for node in tree.body if isinstance(node, ast.ClassDef)}
        )

    settings_classes = {
        name for name, node in classes.items() if _inherits_base_settings(node)
    }
    nested_settings_classes: set[str] = set()
    for name in settings_classes:
        for statement in classes[name].body:
            if isinstance(statement, ast.AnnAssign):
                nested_settings_classes.update(
                    _annotation_names(statement.annotation) & settings_classes
                )
    roots = settings_classes - nested_settings_classes
    names: set[str] = set()

    def visit_fields(
        class_name: str,
        prefix: str,
        nested_delimiter: str | None,
        visiting: frozenset[str],
    ) -> None:
        if class_name in visiting:
            return
        node = classes[class_name]
        next_visiting = visiting | {class_name}
        for statement in node.body:
            if not isinstance(statement, ast.AnnAssign) or not isinstance(
                statement.target, ast.Name
            ):
                continue
            field_name = statement.target.id
            if field_name.startswith("_"):
                continue
            aliases = _field_aliases(statement.value)
            environment_names = aliases or {f"{prefix}{field_name.upper()}"}
            nested_classes = _annotation_names(statement.annotation) & classes.keys()
            if nested_delimiter and nested_classes:
                for environment_name in environment_names:
                    for nested_class in nested_classes:
                        visit_fields(
                            nested_class,
                            f"{environment_name}{nested_delimiter}",
                            nested_delimiter,
                            next_visiting,
                        )
            else:
                names.update(environment_names)

    for root in roots:
        env_prefix, nested_delimiter = _class_config(classes[root])
        visit_fields(root, env_prefix, nested_delimiter, frozenset())
    return names


def parse_environment_example(path: Path) -> tuple[EnvironmentExampleEntry, ...]:
    entries: list[EnvironmentExampleEntry] = []
    for line_number, raw_line in enumerate(
        path.read_text(encoding="utf-8").splitlines(), start=1
    ):
        match = _ENV_DECLARATION.match(raw_line)
        if match is None:
            continue
        stripped = raw_line.lstrip()
        entries.append(
            EnvironmentExampleEntry(
                name=match.group(1),
                value=match.group(2).split("  #", 1)[0].strip(),
                commented=stripped.startswith("#"),
                line=line_number,
            )
        )
    return tuple(entries)


def discover_compose_environment_names(repository_root: Path) -> set[str]:
    names: set[str] = set()
    pattern = re.compile(r"\$\{([A-Z][A-Z0-9_]*)")
    for path in sorted(repository_root.glob("docker-compose*.yml")):
        names.update(pattern.findall(path.read_text(encoding="utf-8")))
    return names


def _expanded_runtime_names(
    source_root: Path,
) -> tuple[set[str], tuple[DynamicEnvironmentAccess, ...]]:
    names, dynamic_accesses = discover_environment_accesses(source_root)
    names.update(discover_settings_environment_names(source_root))
    unresolved: list[DynamicEnvironmentAccess] = []
    for access in dynamic_accesses:
        expanded = _DYNAMIC_ENVIRONMENT_NAMES.get(access.classification_key)
        if expanded is None:
            unresolved.append(access)
        else:
            names.update(expanded)
    return names, tuple(unresolved)


def _unsafe_example_reason(entry: EnvironmentExampleEntry) -> str | None:
    value = entry.value
    if not value:
        return None

    lowered = value.lower()
    if _SECRET_NAME.search(entry.name) and not any(
        marker in lowered for marker in _SAFE_SECRET_MARKERS
    ):
        return "secret-like setting has a non-placeholder example"

    candidate = value
    if "://" in candidate:
        candidate = urlsplit(candidate).hostname or ""
    else:
        candidate = candidate.split("/", 1)[0]

    try:
        address = ipaddress.ip_address(candidate)
    except ValueError:
        address = None
    if address is not None and address.is_private and not address.is_loopback:
        if not address.is_unspecified:
            return "example contains a private network address"

    if re.search(r"(?:^|[./:@])(?:[a-z0-9-]+\.)*aelira\.ai(?:$|[/:])", lowered):
        return "example assumes Aelira's hosted production domain"
    return None


def verify_environment_contract(
    source_root: Path,
    example_path: Path,
) -> list[str]:
    issues: list[str] = []
    runtime_names, unresolved = _expanded_runtime_names(source_root)
    compose_names = discover_compose_environment_names(source_root.parent)
    template_only_names = (
        set(TEMPLATE_ONLY_ENVIRONMENT_NAMES) if compose_names else set()
    )
    entries = parse_environment_example(example_path)
    counts: dict[str, int] = {}
    for entry in entries:
        counts[entry.name] = counts.get(entry.name, 0) + 1

    duplicate_names = sorted(name for name, count in counts.items() if count != 1)
    if duplicate_names:
        issues.append("duplicate .env.example names: " + ", ".join(duplicate_names))

    for access in unresolved:
        issues.append(
            "unclassified dynamic environment access: "
            f"{access.source}:{access.line} {access.scope}({access.expression})"
        )

    public_runtime_names = runtime_names - INTERNAL_ENVIRONMENT_NAMES.keys()
    example_names = set(counts)
    missing = sorted((public_runtime_names | template_only_names) - example_names)
    extra = sorted(example_names - public_runtime_names - template_only_names)
    if missing:
        issues.append("missing from .env.example: " + ", ".join(missing))
    if extra:
        issues.append(
            "not read by runtime or classified template-only: " + ", ".join(extra)
        )

    stale_template_classifications = sorted(template_only_names - compose_names)
    if stale_template_classifications:
        issues.append(
            "template-only classification is not consumed by Compose: "
            + ", ".join(stale_template_classifications)
        )

    for alias, canonical in sorted(LEGACY_ENVIRONMENT_ALIASES.items()):
        if alias in runtime_names and canonical not in public_runtime_names:
            issues.append(
                f"legacy alias {alias} targets absent canonical name {canonical}"
            )
        if alias in example_names and canonical not in example_names:
            issues.append(
                f"documented alias {alias} lacks canonical example {canonical}"
            )

    for entry in entries:
        reason = _unsafe_example_reason(entry)
        if reason is not None:
            issues.append(
                f"unsafe example at line {entry.line} ({entry.name}): {reason}"
            )

    return issues


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, default=REPO_ROOT / "src")
    parser.add_argument("--example", type=Path, default=REPO_ROOT / ".env.example")
    args = parser.parse_args()

    issues = verify_environment_contract(args.source_root, args.example)
    if issues:
        for issue in issues:
            print(f"ERROR: {issue}")
        return 1
    print("Environment contract verified")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
